version: "3"

services:
    app:
        build: .
        ports:
            - "5000:5000"
        restart: always
        command: >
           sh -c "python main.py"
        volumes:
            - .:/app
        environment:
            - FLASK_APP=main.py
            - DB_NAME=flask_main
            - DB_USER=riyad
            - DB_PASSWORD=123456
            - DB_HOST=flask-db
            - DB_PORT=3306  
        depends_on:
            - flask-db
    
    consumer:
        build: .
        restart: always
        volumes:
            - .:/app
        command: >
            sh -c "python consumer.py"
        depends_on:
            - flask-db  

    flask-db:
        image: mysql
        container_name: mysql_flask_main
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "33067:3306"
        environment:
            - MYSQL_DATABASE=flask_main
            - MYSQL_USER=riyad
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - ./db:/var/lib/mysql
    
           